packages:
  - "packages/hub"
  - "packages/inference"
  - "packages/doc-internal"
  - "packages/agents"
  - "packages/languages"
  - "packages/tasks"
  - "packages/gguf"
  - "packages/jinja"
  - "packages/widgets"
