name: Delete doc comment trigger

on:
  pull_request:
    paths:
      - "README.md"
      - "hub/README.md"
      - "inference/README.md"
    types: [closed]

jobs:
  delete:
    uses: huggingface/doc-builder/.github/workflows/delete_doc_comment_trigger.yml@main
    with:
      pr_number: ${{ github.event.number }}
