name: Build documentation

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "README.md"
      - "docs/**"
      - "packages/hub/package.json"
      - "packages/inference/package.json"
      - "packages/agents/package.json"

jobs:
  build:
    uses: huggingface/doc-builder/.github/workflows/build_main_documentation.yml@main
    with:
      commit_sha: ${{ github.sha }}
      package: huggingface.js
      path_to_docs: huggingface.js/docs
      additional_args: --not_python_module
      pre_command: corepack enable && cd huggingface.js && pnpm install && pnpm -r build && pnpm --filter doc-internal start
    secrets:
      hf_token: ${{ secrets.HF_DOC_BUILD_PUSH }}
