name: Build documentation

on:
  push:
    branches:
      - main
    paths:
      - "README.md"
      - "hub/README.md"
      - "hub/package.json"
      - "inference/README.md"
      - "hub/inference.json"

jobs:
  build:
    uses: huggingface/doc-builder/.github/workflows/build_main_documentation.yml@main
    with:
      commit_sha: ${{ github.sha }}
      package: huggingface.js
      path_to_docs: huggingface.js/docs
      additional_args: --not_python_module
      pre_command: npm install -g pnpm@7 && cd huggingface.js && pnpm install && pnpm --filter doc-internal start
