name: Hub - Version and Release

on:
  workflow_dispatch:
    inputs:
      newversion:
        description: "Semantic Version Bump Type (major minor patch)"
        default: patch

defaults:
  run:
    working-directory: packages/hub

jobs:
  version_and_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.BOT_ACCESS_TOKEN }}
      - uses: pnpm/action-setup@v2
        with:
          version: 7.1.5
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "pnpm"
          cache-dependency-path: |
            packages/hub/pnpm-lock.yaml
            packages/doc-internal/pnpm-lock.yaml
          # setting a registry enables the NODE_AUTH_TOKEN env variable where we can set an npm token.  REQUIRED
          registry-url: "https://registry.npmjs.org"
      - run: pnpm install
      - run: git config --global user.name machineuser
      - run: git config --global user.email tech@huggingface.co
      - run: yarn config set version-git-message "🔖 @hugginface/hub v%s"
      - run: yarn config set version-tag-prefix "hub-v"
      - run: yarn version --${{ github.event.inputs.newversion }}
      - run: cd ../doc-internal && pnpm install && pnpm run prepublish-hub
      - run: cd ../../ && git add . && git commit --amend --no-edit
      - run: pnpm publish .
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: git push --follow-tags

  publish-gpr:
    name: 'Publish Package to GitHub Package Registry'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 'latest'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'pnpm'
          cache-dependency-path: 'packages/hub/pnpm-lock.yaml'
          registry-url: 'https://npm.pkg.github.com'

      - name: Install Dependencies
        working-directory: packages/hub
        run: pnpm install --frozen-lockfile

      - name: Update ~/.npmrc
        run: |
          echo "//npm.pkg.github.com:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc

      - name: 'Publish'
        working-directory: packages/hub
        env:
          NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pnpm publish --access public --registry https://npm.pkg.github.com --no-git-checks