name: Build PR Documentation

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    uses: huggingface/doc-builder/.github/workflows/build_pr_documentation.yml@pre-command
    with:
      commit_sha: ${{ github.event.pull_request.head.sha }}
      pr_number: ${{ github.event.number }}
      package: huggingface.js
      path_to_docs: huggingface.js/docs
      pre_command: "npm install -g n && n 18 && npm install -g pnpm && cd huggingface.js && pnpm install && pnpm --filter doc-internal start"
      additional_args: --not_python_module
