name: Build PR Documentation

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    uses: huggingface/doc-builder/.github/workflows/build_pr_documentation.yml@main
    with:
      commit_sha: ${{ github.sha }}
      pr_number: ${{ github.event.number }}
      package: huggingface.js
      path_to_docs: huggingface.js/docs
      pre_command: npm install -g pnpm && cd huggingface.js && pnpm install && pnpm --filter doc-internal start
      additional_args: --not_python_module
    secrets:
      token: ${{ secrets.HF_DOC_TOKEN }}
